const assert = require('node:assert/strict');
const fs = require('node:fs');
const crypto = require('node:crypto');
/** Runs only on a fictional factory in the separate testing project. */
module.exports = async function featureFlows(owner, browser, credentials, origin) {
  const { evaluateFlow } = await import('../src/utils/production-flow.mjs');
  const checks = [];
  const recordCheck = checks.push.bind(checks);
  checks.push = (...items) => { const count = recordCheck(...items); console.log(items.join('; ')); fs.writeFileSync('test-results/feature-flow-progress.json', JSON.stringify({checks},null,2)); return count; };
  const get = async (client, suffix = '') => {
    const r = await client.get(origin + '/api/data' + suffix,{timeout:120000});
    assert.equal(r.status(), 200, 'snapshot response');
    return r.json();
  };
  let initial = await get(owner);
  assert.equal(initial.factory.is_demo, true, 'only fictional factory may be changed by this test');
  const factory = initial.factory.id;
  const call = async (client, command, args) => {
    const r = await client.post(origin + '/api/data', { timeout: 120000, headers: { origin }, data: { command, args: { factory, ...args } } });
    const result = await r.json();
    assert.equal(r.status(), 200, command + ': ' + (result.error || ''));
    return result.data;
  };
  const callFail = async (client, command, args, expected) => {
    const r = await client.post(origin + '/api/data', { timeout: 120000, headers: { origin }, data: { command, args: { factory, ...args } } });
    const result = await r.json();
    assert.equal(r.status(), 400, command + ' must be rejected');
    assert.equal(result.error, expected, command + ' error mapping');
    return result;
  };
  const save = (resource, payload, id = null) => call(owner, 'save_record', { resource, id, payload });
  const stamp = 'QA-' + Date.now().toString(36);
  const area = await save('factory', { name: stamp + ' area', name_ar: 'منطقة اختبار وظيفي' });
  const line = await save('lines', { name: stamp + ' line', name_ar: 'خط اختبار', code: stamp + '-L', area_id: area });
  const cell = await save('centers', { name: stamp + ' cell', name_ar: 'خلية اختبار', code: stamp + '-CELL', type: 'production_cell', area_id: area, line_id: line });
  const center = await save('centers', { name: stamp + ' table', name_ar: 'طاولة اختبار', code: stamp + '-TABLE', type: 'assembly_table', area_id: area, line_id: line, parent_id: cell });
  const spare = await save('centers', { name: stamp + ' spare', name_ar: 'آلة بديلة للاختبار', code: stamp + '-SPARE', type: 'assembly_table', area_id: area });
  checks.push('Create area, line, production cell, child manual table and idle spare machine');
  const product = await save('products', { name: stamp + ' pipe', name_ar: 'أنبوب اختبار', code: stamp + '-P', unit: 'unit', diameter: 25, length: 6, standard_rate: 300 });
  const order = await save('orders', { code: stamp + '-ORDER', product_id: product, line_id: line, status: 'active', target_quantity: 100, start_time: new Date().toISOString(), expected_finish: new Date(Date.now() + 3600000).toISOString() });
  const operator = initial.tables.memberships.find(m => m.display_name === 'Omar Khalil');
  await save('centers', { order_id: order, operator_id: operator.id }, center);
  await call(owner, 'configure_center_links', { work_center: center, alternatives: [spare], capabilities: [{ product_id: product, rate: 300 }] });
  let snapshot = await get(owner);
  assert.ok(snapshot.tables.work_center_capabilities.some(c => c.work_center_id === center && c.product_id === product));
  assert.ok(snapshot.tables.operator_assignments.some(a => a.work_center_id === center && a.operator_id === operator.id));
  checks.push('Product, order, operator assignment, capabilities and alternatives persist');
  // Layout saves are versioned: the current structure_version saves and moves machines, stale versions are rejected without overwriting.
  const arrange = (impactScope) => snapshot.tables.work_centers.filter(c => !c.archived).map(c => {
    const inLine = c.line_id === line;
    return { id: c.id, line_id: c.line_id, position: inLine ? (c.id === cell ? 0 : 1) : Number(c.position || 0), dependency_mode: inLine ? 'blocking' : String(c.dependency_mode || 'independent'), buffer_minutes: Number(c.buffer_minutes || 0), impact_scope: inLine ? impactScope : String(c.impact_scope || 'none') };
  });
  const currentVersion = snapshot.factory.structure_version;
  await call(owner, 'save_line_layout', { version: currentVersion, layout: arrange('whole_line') });
  snapshot = await get(owner);
  const savedVersion = snapshot.factory.structure_version;
  assert.ok(savedVersion > currentVersion, 'valid layout save advances the structure version');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === cell).position, 0, 'upstream machine position saved');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === center).position, 1, 'stopped machine position saved');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === center).impact_scope, 'whole_line', 'impact scope saved');
  await callFail(owner, 'save_line_layout', { version: currentVersion, layout: arrange('none').map(x => x.id === center ? { ...x, line_id: null, position: 7, dependency_mode: 'independent' } : x) }, 'layoutConflict');
  snapshot = await get(owner);
  assert.equal(snapshot.factory.structure_version, savedVersion, 'rejected stale save does not advance the structure version');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === center).line_id, line, 'rejected stale save does not overwrite the layout');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === center).impact_scope, 'whole_line', 'newer arrangement survives a stale rejection');
  checks.push('Layout save moves machines, advances the structure version and rejects stale drafts without overwriting');
  await call(owner, 'change_status', { work_center: center, status: 'running' });
  const reason = initial.tables.downtime_reasons.find(r => r.name === 'Mechanical Failure');
  const sub = initial.tables.downtime_reasons.find(r => r.parent_id === reason.id);
  await call(owner, 'change_status', { work_center: center, status: 'stopped', reason: reason.id, sub_reason: sub?.id || null, notes: 'Functional test bearing replacement', expected_restart: new Date(Date.now() + 3600000).toISOString(), responsible: operator.id });
  snapshot = await get(owner);
  const stop = snapshot.tables.downtime_events.find(e => e.work_center_id === center && !e.ended_at);
  assert.ok(stop, 'open downtime recorded for the stopped machine');
  await call(owner, 'update_downtime', { id: stop.id, expected_restart: new Date(Date.now() + 7200000).toISOString(), notes: 'Functional test revised restart plan', responsible: operator.id });
  // The legacy transferred flag is no longer accepted; operational transfers use the transfer command.
  await callFail(owner, 'change_status', { work_center: center, status: 'stopped', reason: reason.id, transferred: true }, 'useTransferCommand');
  await callFail(owner, 'update_downtime', { id: stop.id, notes: 'Functional test legacy flag', transferred: true }, 'useTransferCommand');
  const transfer = await call(owner, 'transfer_production', { work_center: center, alternative: spare, reason: 'Functional test transfer to spare machine' });
  snapshot = await get(owner);
  const transferRow = () => snapshot.tables.production_transfers.find(x => x.id === transfer);
  assert.ok(transferRow() && transferRow().original_id === center && transferRow().alternative_id === spare && transferRow().order_id === order, 'transfer recorded with original, alternative and order');
  assert.ok(!transferRow().ended_at && !transferRow().original_returned_at, 'transfer open');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === spare).status, 'running', 'configured alternative started');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === spare).order_id, order, 'alternative carries the active order');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === center).status, 'stopped', 'original machine remains physically stopped');
  const duringTransfer = snapshot.tables.downtime_events.find(e => e.id === stop.id);
  assert.ok(!duringTransfer.ended_at && duringTransfer.transferred === true && duringTransfer.alternative_id === spare, 'transfer annotates the open downtime');
  assert.match(duringTransfer.notes, /revised/, 'downtime history remains intact');
  const activeFlow = evaluateFlow(snapshot.tables.work_centers.filter(c => !c.archived), snapshot.tables.downtime_events, snapshot.tables.production_transfers);
  assert.equal(activeFlow[center].state, 'transferred', 'stopped original shown as transferred');
  assert.equal(activeFlow[cell].state, 'clear', 'active transfer mitigates whole-line impact');
  assert.equal(activeFlow[spare].state, 'clear', 'alternative itself stays unblocked');
  checks.push('Operational transfer runs the configured spare, mitigates whole-line impact and keeps the original stopped');
  await call(owner, 'change_status', { work_center: spare, status: 'stopped', reason: reason.id, notes: 'Functional test alternative interrupted' });
  snapshot = await get(owner);
  assert.ok(transferRow().ended_at, 'alternative stop ends the transfer');
  assert.ok(!transferRow().original_returned_at, 'alternative stop does not imply the original returned');
  assert.equal(snapshot.tables.work_centers.find(c => c.id === center).status, 'stopped', 'original still physically stopped after interruption');
  const interruptedFlow = evaluateFlow(snapshot.tables.work_centers.filter(c => !c.archived), snapshot.tables.downtime_events, snapshot.tables.production_transfers);
  assert.equal(interruptedFlow[center].state, 'blocked', 'stopped original blocks again');
  assert.equal(interruptedFlow[cell].state, 'blocked', 'whole-line impact effective again');
  checks.push('Alternative interruption ends mitigation and the whole-line impact becomes effective again');
  await call(owner, 'change_status', { work_center: center, status: 'running' });
  snapshot = await get(owner);
  assert.ok(transferRow().original_returned_at && transferRow().ended_at, 'original return recorded and transfer closed');
  const returnedFlow = evaluateFlow(snapshot.tables.work_centers.filter(c => !c.archived), snapshot.tables.downtime_events, snapshot.tables.production_transfers);
  assert.equal(returnedFlow[cell].state, 'clear', 'returned original clears the line');
  checks.push('Original return is recorded in the transfer history');
  const output = { work_center: center, production_order: order, produced: 11, rejected: 1, notes: 'Functional test output', request_id: crypto.randomUUID() };
  await call(owner, 'record_output', output);
  await call(owner, 'record_output', output);
  const today = new Intl.DateTimeFormat('en-CA', {timeZone:initial.factory.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  await call(owner, 'set_daily_target', { production_order: order, day: today, target: 11 });
  snapshot = await get(owner);
  assert.equal(snapshot.tables.production_orders.find(o => o.id === order).produced_quantity, 11);
  assert.equal(snapshot.tables.status_events.filter(e => e.work_center_id === center).length, 3);
  assert.ok(snapshot.tables.downtime_events.find(e => e.id === stop.id).ended_at);
  assert.ok(snapshot.tables.daily_targets.some(t => t.order_id === order && t.target === 11));
  checks.push('Stop, subreason, revised restart plan and resume preserve history');
  checks.push('Production output is counted once on retry; daily target persists');
  const csv = await owner.post(origin + '/api/export', {timeout:120000,headers:{origin},data:{factory,period:'today',area,line,machine:center,reason:reason.id,lang:'ar'}});
  assert.equal(csv.status(),200);assert.match(csv.headers()['content-type'],/text\/csv/);assert.match(await csv.text(),/طاولة اختبار/);
  checks.push('Filtered Arabic CSV export includes the tested downtime');
  checks.push(...await require('./feature-flow-administration.cjs')({owner,browser,credentials,origin,initial,factory,call,get,save,stamp,center,cell,line,area,order,operator}));
  fs.writeFileSync('test-results/feature-flow-results.json',JSON.stringify({checkedAt:new Date().toISOString(),checks},null,2));
  return checks;
};
